id: c328b0e9b634441780c65972ebb3ff9b
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_164-The_Questions_of_Ratnacandra-v2
  language: bo
  author: ''
  volume: {}
